#!/usr/bin/env bash

if [ $# -lt 2 ]; then
    exit 1
fi

suffix="$1"
shift

for file in "$@"; do

    if [ ! -f "$file" ]; then
	echo "no file" >&2
        continue
    fi
    
    mv "$file" "${file}${suffix}"
done
